// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDankx6P2xnR4eysceLlsJJMXYYGqlWjXw',
    appId: '1:478610537234:web:5c45f0b0bb0beae3bd51cb',
    messagingSenderId: '478610537234',
    projectId: 'studentsdetails2',
    authDomain: 'studentsdetails2.firebaseapp.com',
    storageBucket: 'studentsdetails2.appspot.com',
    measurementId: 'G-JBZSN4K8WW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYcbCdEbvSKo7KK1NjheLcr-R4SczOExM',
    appId: '1:478610537234:android:675d17b78ed6de29bd51cb',
    messagingSenderId: '478610537234',
    projectId: 'studentsdetails2',
    storageBucket: 'studentsdetails2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm2jtKPLWeIrLG4BqzzfAbIoUKQKhkoQ4',
    appId: '1:478610537234:ios:8b3420b1460bea79bd51cb',
    messagingSenderId: '478610537234',
    projectId: 'studentsdetails2',
    storageBucket: 'studentsdetails2.appspot.com',
    iosBundleId: 'com.example.studentsDetailsFirebase2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm2jtKPLWeIrLG4BqzzfAbIoUKQKhkoQ4',
    appId: '1:478610537234:ios:8242ab363eac724fbd51cb',
    messagingSenderId: '478610537234',
    projectId: 'studentsdetails2',
    storageBucket: 'studentsdetails2.appspot.com',
    iosBundleId: 'com.example.studentsDetailsFirebase2.RunnerTests',
  );
}
